### ISSUE TITLE
APD Noise generator class

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#121]
This task is related to #97 noise modelling and build on the developed Noise class featured in #120, which is a parent class to APD.
Using the noise generation routines available in Noise. The APD class will create an accurate noisy signal version based on ph/s input data.

Unittesting of the APD class is related to issue: #126

**Comment by asztalosors** [comment]
There seems to be a problem with the instantiation of an APD detector class.:

Traceback (most recent call last):
  File "D:\Software\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-c411d2d9ad9e>", line 1, in <module>
    det.add_noise_to_signal(sig)
  File "D:\Codes\RenateOD\observation\noise.py", line 125, in add_noise_to_signal
    self.noise_index, self.bandwidth)
TypeError: shot_noise_generator() missing 1 required positional argument: 'quantum_efficiency'

**Comment by asztalosors** [comment]
APD Noise generation class is as good as done. The Class generates the gaussian type of noise. Further noise implementations are pending.
