### ISSUE TITLE
Atomic db reading error.

### ISSUE THREAD

**Issue by Balazs-Peter** [gergopokol/renate-od#169]
While running development branch, creating a beamlet with the default settings failed.

Traceback (most recent call last):

  File "D:\plazma\renate-od\rod_test.py", line 3, in <module>
    b=Beamlet()

  File "D:\plazma\renate-od\crm_solver\beamlet.py", line 24, in __init__
    self.atomic_db = AtomicDB(param=self.param, components=self.components)

  File "D:\plazma\renate-od\crm_solver\atomic_db.py", line 126, in __init__
    RenateDB.__init__(self, param, rate_type, data_path)

  File "D:\plazma\renate-od\crm_solver\atomic_db.py", line 20, in __init__
    self.__set_charge_state_lib()

  File "D:\plazma\renate-od\crm_solver\atomic_db.py", line 81, in __set_charge_state_lib
    for state in range(impact_loss.shape[0]-1):

AttributeError: 'str' object has no attribute 'shape'

**Comment by asztalosors** [comment]
The issue seems the following. 
Örs env: Python 3.6.4 With h5py: 2.7.1
Peter env: Python 3.7.9 With h5py: 3.2.1

Return error for command: utility.getdata line: 93: The value command returns an Attribute error. for the newer version of h5py.
