### ISSUE TITLE
Minor clean-up tasks in preparation for the dissolution of the noise modelling branch.

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#173]
1. Activate RegressionTests
2. Fix data key name.

More to come.

**Comment by asztalosors** [comment]
Build #554 Failed.  For two tests:
1. Regression test crm: 

======================================================================
FAIL: test_actual_to_previous_release (crm_solver.crmsystemtest.CrmRegressionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/gergopokol/renate-od/crm_solver/crmsystemtest.py", line 37, in test_actual_to_previous_release
    self.assertAlmostEqualRateEvolution(actual, reference, msg=msg)
  File "/home/travis/build/gergopokol/renate-od/crm_solver/crmtestcase.py", line 39, in assertAlmostEqualRateEvolution
    self.fail(msg)
AssertionError: Population evolution on level 3s are not within relative error of 0.001. Series 1 = actual, Series 2 = reference 
Value Series 1, 	 Value Series 2, 	 Almost Equal
 6802257967.125763, 	 6802258819.289039, 	 True
 6787253646.471936, 	 6787254496.82805, 	 True
 6763431537.679354, 	 6763432386.415509, 	 True
 6717690272.345873, 	 6717691110.121932, 	 True
 6638160460.632212, 	 6638161293.701358, 	 True
 6520440020.186557, 	 6520440829.834626, 	 True
 6320178443.034248, 	 6320179230.469275, 	 True
 5963703191.7336445, 	 5963703916.576521, 	 True
 5329188566.941708, 	 5329189196.405524, 	 True
 4158066070.270575, 	 4158066601.761976, 	 True
 2799732495.882833, 	 2799732814.867008, 	 True
 1808092631.2698646, 	 1808092849.8430502, 	 True
 1176294956.0616922, 	 1176295110.3240838, 	 True
 758958598.011476, 	 758958703.7939551, 	 True
 483489508.62398005, 	 483489564.9344368, 	 True
 303747734.77288514, 	 303747766.86460924, 	 True
 188346764.53527325, 	 188346784.2108972, 	 True
 115582610.17568278, 	 115582619.5036291, 	 True
 70401584.78133772, 	 70401591.94651857, 	 True
 42664099.36791199, 	 42664103.654993564, 	 True
 25754279.887144823, 	 25754282.554384984, 	 True
 15481586.119558966, 	 15481586.285133792, 	 True
 9265994.079178652, 	 9265994.325615037, 	 True
 5519176.120773993, 	 5519175.512179488, 	 True
 3271021.5638738438, 	 3271020.820242686, 	 True
 1929419.641830935, 	 1929419.052947657, 	 True
 1132083.640117746, 	 1132083.1779640007, 	 True
 660860.8002097182, 	 660860.502173392, 	 True
 383937.7220557215, 	 383937.5231843822, 	 True
 221883.21650201292, 	 221883.0923943588, 	 True
 127564.53762423225, 	 127564.47336967483, 	 True
 72991.57015648588, 	 72991.53332976413, 	 True
 41551.187638236755, 	 41551.16701677908, 	 True
 23530.735911676526, 	 23530.725144399417, 	 True
 13262.28642096663, 	 13262.28035350254, 	 True
 7440.162053423807, 	 7440.158355956119, 	 True
 4153.223078511761, 	 4153.221015215816, 	 True
 2307.028524752964, 	 2307.027398569429, 	 True
 1275.3114357892189, 	 1275.3107573548352, 	 True
 701.6064748185036, 	 701.6061066107989, 	 True
 384.229471388793, 	 384.22928154861614, 	 True
 209.45856597843388, 	 209.45846521280137, 	 True
 113.6648465367669, 	 113.66479012333265, 	 True
 61.40257226659371, 	 61.4025403017693, 	 True
 33.03333295517984, 	 33.033315274304, 	 True
 17.697784232386386, 	 17.69777492923227, 	 True
 9.439040081817375, 	 9.439035247511251, 	 True
 5.012314117694702, 	 5.012311863158604, 	 True
 2.651170992267706, 	 2.6511698271205093, 	 True
 1.3967029082223439, 	 1.3967023331219972, 	 True
 0.7329352160526946, 	 0.7329349066427775, 	 True
 0.38361562070590244, 	 0.3836153550984841, 	 True
 0.19986257481269215, 	 0.19986246186959378, 	 True
 0.10341884657894407, 	 0.10341877329295605, 	 True
 0.0533975200519988, 	 0.05339748384085908, 	 True
 0.02749554108881722, 	 0.027495470700564868, 	 True
 0.014123837112286448, 	 0.014123821419236763, 	 True
 0.007234718548283109, 	 0.007234713657053353, 	 True
 0.0036806786603958445, 	 0.003680649018454164, 	 True
 0.001868492871357093, 	 0.0018684233334020509, 	 True
 0.0009461284594868552, 	 0.0009460829363689243, 	 True
 0.00047794760757652354, 	 0.00047793898142717685, 	 True
 0.00024077338409451082, 	 0.0002407729572787841, 	 True
 0.0001210027760078054, 	 0.00012101599267137214, 	 True
 6.064086655883686e-05, 	 6.0658453094691345e-05, 	 True
 3.0196278429730335e-05, 	 3.021846950479415e-05, 	 True
 1.5005263593777324e-05, 	 1.5024515626007929e-05, 	 False
 7.439217604219161e-06, 	 7.453706080874707e-06, 	 False
 3.6761466051225625e-06, 	 3.6894750440286302e-06, 	 False : Failure for following test case: scenario-standard_plasma-H_energy-100_beam-Na_profile

2. Noise test:

======================================================================
FAIL: test_voltage_noise_generator (observation.noisetest.NoiseGeneratorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/gergopokol/renate-od/observation/noisetest.py", line 326, in test_voltage_noise_generator
    msg='The Voltage Noise Generator does not return expected mean value')
  File "/home/travis/build/gergopokol/renate-od/observation/noisetest.py", line 56, in assertDistributionMean
    self.fail(msg)
AssertionError: 
 Actual distribution function mean: 	 0.010632565408594929 and 
 reference mean: 	 0 are not within precision margin. 
Actual precision: 	 0.010632565408594929, Reference precision: 	 0.01. 
 : The Voltage Noise Generator does not return expected mean value

**Comment by asztalosors** [comment]
In both cases raising the precision is justified.
1. Regression testing: all test pass (H,D,T,Li) beams and almost all of the Na beam. It is clear that at the beam end, where the electron population is very scarce, which is not relevant.
2. For the second case the actual precision is 6% higher than the allotted value for random generation processes. Should not be an issue.

**Comment by asztalosors** [comment]
All outstanding issues are minor bugs are fixed. Anything new creeping should be investigated in the pull request. Recommend closing issue.
