### ISSUE TITLE
Bug in data access from deep.

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#51]
There seems to be an issue with data acquisition from the deep server.
Traceback (most recent call last):
  File "D:\Software\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-c7ea594a429e>", line 1, in <module>
    b = Beamlet(data_path='beamlet/testimp0001.xml')
  File "D:\Codes\ROD\crm_solver\beamlet.py", line 16, in __init__
    self.read_beamlet_param(data_path)
  File "D:\Codes\ROD\crm_solver\beamlet.py", line 31, in read_beamlet_param
    self.param = utility.getdata.GetData(data_path_name=data_path).data
  File "D:\Codes\ROD\utility\getdata.py", line 45, in __init__
    self.read_data()
  File "D:\Codes\ROD\utility\getdata.py", line 88, in read_data
    raise OSError
OSError

**Comment by asztalosors** [comment]
Issue fixed.
