### ISSUE TITLE
Regression test fail on CI Travis

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#80]
Regression test fails.
1. Test fail under CI Travis platform.
2. Test runs successfully in local environment.

**Comment by asztalosors** [comment]
Travis error message:

ModuleNotFoundError: No module named 'tables'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/gergopokol/renate-od/crm_solver/beamlettest.py", line 14, in test_renate_rod_benchmark
    actual = Beamlet(data_path=self.INPUT_TESTCASES[testcase])
  File "/home/travis/build/gergopokol/renate-od/crm_solver/beamlet.py", line 22, in __init__
    self.__read_beamlet_profiles()
  File "/home/travis/build/gergopokol/renate-od/crm_solver/beamlet.py", line 35, in __read_beamlet_profiles
    self.components = utility.getdata.GetData(data_path_name=hdf5_path, data_key=['components']).data
  File "/home/travis/build/gergopokol/renate-od/utility/getdata.py", line 45, in __init__
    self.read_data()
  File "/home/travis/build/gergopokol/renate-od/utility/getdata.py", line 78, in read_data
    self.read_h5_to_pandas()
  File "/home/travis/build/gergopokol/renate-od/utility/getdata.py", line 100, in read_h5_to_pandas
    self.data = pandas.read_hdf(self.access_path, key=self.data_key[0])
  File "/home/travis/virtualenv/python3.6.4/lib/python3.6/site-packages/pandas/io/pytables.py", line 349, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, **kwargs)
  File "/home/travis/virtualenv/python3.6.4/lib/python3.6/site-packages/pandas/io/pytables.py", line 448, in __init__
    'importing'.format(ex=str(ex)))
ImportError: HDFStore requires PyTables, "No module named 'tables'" problem importing

**Comment by asztalosors** [comment]
The error propagates from: 
self.data = pandas.read_hdf(self.access_path, key=self.data_key[0])

Located in line 100 of utility.getdata.py
An import error is thrown. As the error occurs on Travis CI and not local indicates an environment issue. Needs be tested on various platforms of python to confirm.

**Comment by asztalosors** [comment]
Unittesting works. Pandas has a dependency on tables. It would be highly beneficial to install anaconda on the CI platform, otherwise this will not be the last instance of errors as such occurring.
